### ISSUE TITLE
Does Not Work With SSH Connections

### ISSUE THREAD

**Issue by seanelble** [redfox-tools/bamboo-github-status#2]
We really like this plugin, but we also prefer to use SSH connections to our source control systems. In trying to use this plugin with SSH, we see errors like this:

```
2020-02-28 14:17:53,069 ERROR [6-DelayedChangeDetectionThread:pool-12-thread-12737] [GitHubService] Failed to update GitHub status
java.net.MalformedURLException: Unknown protocol: ssh
```

In taking a very quick look at the code, it _seems_ like it may only support HTTPS connections. Is that true, and if so, is there any chance of a patch to fix this?

**Comment by IGx89** [comment]
👍 

Here's the stack trace we're seeing, same issue with git URLs:

```
2020-07-14 09:15:27,320 ERROR [AtlassianEvent::0-BAM::EVENTS:pool-2-thread-4] [GitHubService] Failed to update GitHub status
java.net.MalformedURLException: no protocol: git@github.com:xxx/yyy.git
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at tools.redfox.bamboo.github.status.service.GitHubService.getRelativePath(GitHubService.java:91)
	at tools.redfox.bamboo.github.status.service.GitHubService.getGHRepository(GitHubService.java:81)
	at tools.redfox.bamboo.github.status.service.GitHubService.setStatus(GitHubService.java:53)
	at tools.redfox.bamboo.github.status.action.AbstractGitHubStatusAction.pushUpdate(AbstractGitHubStatusAction.java:52)
	at tools.redfox.bamboo.github.status.action.GitHubStatusPostStage.execute(GitHubStatusPostStage.java:49)
```

**Comment by IGx89** [comment]
@mprzytulski, would you accept a PR to fix this issue, if I'm able to find a fix myself?

**Comment by IGx89** [comment]
I ended up working around the issue by switching from a git URL and SSH key to an HTTPS URL and username/password (PAT) combo. It's easy enough to fix the above-mentioned bug, however after looking through the code I saw it would simply error out later due to it being impossible to use an SSH key to make GitHub API calls.
